#pragma once
#include "cinder/CinderResources.h"

#define RES_WHIRLPOOL CINDER_RESOURCE( ../resources/, whirlpool.png, 128, IMAGE )
#define RES_BACKGROUND CINDER_RESOURCE( ../resources/, bg.png, 128, IMAGE )
#define RES_CURSOR CINDER_RESOURCE( ../resources/, cursor.png, 128, IMAGE )

#define RES_SHADOW_1200x810 CINDER_RESOURCE( ../resources/shadows/, 1200x810.png, 128, IMAGE )
#define RES_SHADOW_240x540 CINDER_RESOURCE( ../resources/shadows/, 240x540.png, 128, IMAGE )
#define RES_SHADOW_480x540 CINDER_RESOURCE( ../resources/shadows/, 480x540.png, 128, IMAGE )
#define RES_SHADOW_480x810 CINDER_RESOURCE( ../resources/shadows/, 480x810.png, 128, IMAGE )
#define RES_SHADOW_720x1080 CINDER_RESOURCE( ../resources/shadows/, 720x1080.png, 128, IMAGE )
#define RES_SHADOW_720x540 CINDER_RESOURCE( ../resources/shadows/, 720x540.png, 128, IMAGE )
#define RES_SHADOW_960x810 CINDER_RESOURCE( ../resources/shadows/, 960x810.png, 128, IMAGE )

#define RES_Matrix_Reloaded_Wallpaper3 CINDER_RESOURCE( ../resources/movie_posters/, (311009004425)Matrix_Reloaded_Wallpaper3.jpg, 128, IMAGE )
#define RES_04 CINDER_RESOURCE( ../resources/movie_posters/, 04.jpg, 128, IMAGE )
#define RES_1166952147_1024x768_movie_stills_of_eternal_sunshine_of_the_spotless_mind CINDER_RESOURCE( ../resources/movie_posters/, 1166952147_1024x768_movie-stills-of-eternal-sunshine-of-the-spotless-mind.jpg, 128, IMAGE )
#define RES_1287369723_1024x768_sleepy_hollow_poster CINDER_RESOURCE( ../resources/movie_posters/, 1287369723_1024x768_sleepy-hollow-poster.jpg, 128, IMAGE )
#define RES_2001_space_odyssey_1280x1048 CINDER_RESOURCE( ../resources/movie_posters/, 2001-space-odyssey_1280x1048.jpg, 128, IMAGE )
#define RES_2007_sunshine_2 CINDER_RESOURCE( ../resources/movie_posters/, 2007-sunshine-2.jpg, 128, IMAGE )
#define RES_2010_movie_poster_year_we_make_contact CINDER_RESOURCE( ../resources/movie_posters/, 2010_movie_poster_year_we_make_contact.jpg, 128, IMAGE )
#define RES_936full_solaris_poster_1 CINDER_RESOURCE( ../resources/movie_posters/, 936full-solaris-poster-1.jpg, 128, IMAGE )
#define RES_936full_solaris_poster CINDER_RESOURCE( ../resources/movie_posters/, 936full-solaris-poster.jpg, 128, IMAGE )
#define RES_Jim_Carrey_in_A_Christmas_Carol_Wallpaper_2_800 CINDER_RESOURCE( ../resources/movie_posters/, Jim_Carrey_in_A_Christmas_Carol_Wallpaper_2_800.jpg, 128, IMAGE )
#define RES_Little_Miss_Sunshine_by_lakikaki CINDER_RESOURCE( ../resources/movie_posters/, Little_Miss_Sunshine_by_lakikaki.jpg, 128, IMAGE )
#define RES_MOON_Poster_by_pepperberetta CINDER_RESOURCE( ../resources/movie_posters/, MOON_Poster_by_pepperberetta.jpg, 128, IMAGE )
#define RES_Movie_Poster_Aliens CINDER_RESOURCE( ../resources/movie_posters/, Movie-Poster-Aliens[1].jpg, 128, IMAGE )
#define RES_Movie_Poster_Liar_Liar CINDER_RESOURCE( ../resources/movie_posters/, Movie-Poster-Liar-Liar.jpg, 128, IMAGE )
#define RES_Nine_movie_still_3 CINDER_RESOURCE( ../resources/movie_posters/, Nine-movie-still-3.jpg, 128, IMAGE )
#define RES_Terminator_2_Judgment_Day_movie_poster CINDER_RESOURCE( ../resources/movie_posters/, Terminator-2-Judgment-Day-movie-poster.jpg, 128, IMAGE )
#define RES_The_Fountain_the_fountain_5530120_1280_1024 CINDER_RESOURCE( ../resources/movie_posters/, The-Fountain-the-fountain-5530120-1280-1024.jpg, 128, IMAGE )
#define RES_The_Matrix_Reloaded_poster CINDER_RESOURCE( ../resources/movie_posters/, The_Matrix_Reloaded_poster.jpg, 128, IMAGE )
#define RES_True_Lies_lobby_card_Arnold_Schwarzenegger_Jamie_Lee_Curtis_James_Cameron_1994_TV_remake CINDER_RESOURCE( ../resources/movie_posters/, True_Lies_lobby_card_Arnold_Schwarzenegger_Jamie_Lee_Curtis_James_Cameron_1994_TV_remake.jpg, 128, IMAGE )
#define RES_alice_in_wonderland_xlg CINDER_RESOURCE( ../resources/movie_posters/, alice_in_wonderland_xlg.jpg, 128, IMAGE )
#define RES_alien3 CINDER_RESOURCE( ../resources/movie_posters/, alien3.jpg, 128, IMAGE )
#define RES_avatar_poster_frensc CINDER_RESOURCE( ../resources/movie_posters/, avatar-poster-frensc.jpg, 128, IMAGE )
#define RES_avatar_poster CINDER_RESOURCE( ../resources/movie_posters/, avatar-poster.jpg, 128, IMAGE )
#define RES_blackswan_poster CINDER_RESOURCE( ../resources/movie_posters/, blackswan_poster.jpg, 128, IMAGE )
#define RES_close_encounters_of_the_third_kind_1_1024 CINDER_RESOURCE( ../resources/movie_posters/, close-encounters-of-the-third-kind-1-1024.jpg, 128, IMAGE )
#define RES_corpse_bride_6_1024 CINDER_RESOURCE( ../resources/movie_posters/, corpse-bride-6-1024.jpg, 128, IMAGE )
#define RES_greenhornet CINDER_RESOURCE( ../resources/movie_posters/, greenhornet.jpg, 128, IMAGE )
#define RES_mpamoonposter2b CINDER_RESOURCE( ../resources/movie_posters/, mpamoonposter2b.jpg, 128, IMAGE )
#define RES_mpayesmanposterb CINDER_RESOURCE( ../resources/movie_posters/, mpayesmanposterb.jpg, 128, IMAGE )
#define RES_sweeneytodd CINDER_RESOURCE( ../resources/movie_posters/, sweeneytodd.jpg, 128, IMAGE )
#define RES_terminator_salvation_poster2 CINDER_RESOURCE( ../resources/movie_posters/, terminator-salvation-poster2.jpg, 128, IMAGE )
#define RES_terminator_poster4 CINDER_RESOURCE( ../resources/movie_posters/, terminator_poster4.jpg, 128, IMAGE )
#define RES_terminator_salvation_21 CINDER_RESOURCE( ../resources/movie_posters/, terminator_salvation_21.jpg, 128, IMAGE )
#define RES_the_mask_original CINDER_RESOURCE( ../resources/movie_posters/, the-mask-original.jpg, 128, IMAGE )
#define RES_the_abyss_1989 CINDER_RESOURCE( ../resources/movie_posters/, the_abyss_1989.jpg, 128, IMAGE )
#define RES_the_nightmare_before_christmas_poster CINDER_RESOURCE( ../resources/movie_posters/, the_nightmare_before_christmas_poster.jpg, 128, IMAGE )
#define RES_titanic_ver2_xlg CINDER_RESOURCE( ../resources/movie_posters/, titanic_ver2_xlg.jpg, 128, IMAGE )
#define RES_vintage_alien_movie_poster CINDER_RESOURCE( ../resources/movie_posters/, vintage-alien-movie-poster.jpg, 128, IMAGE )
#define RES_viral_batman_poster CINDER_RESOURCE( ../resources/movie_posters/, viral-batman-poster.jpg, 128, IMAGE )
